# Dependencies
markdown:         redcarpet
highlighter:      true

# Permalinks
permalink:        pretty

# Setup
title:            buglix.org
tagline:          'Emil Erlandsson'
description:      'The personal blog of Emil Erlandsson'
url:              http://buglix.org
baseurl:          '/'
paginate:         5

author:
  name:           'Emil Erlandsson'
  url:            https://twitter.com/emilerl

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/emilerl

gems:
  - jekyll-sitemap
  - jekyll-paginate

plugins: [jekyll-paginate]