# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            buglix.org
tagline:          'Random rants'
description:      'The personal blog of Emil Erlandsson'
url:              http://buglix.org
baseurl:          '/'
paginate:         5

author:
  name:           'Emil Erlandsson'
  url:            https://twitter.com/emilerl

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/emilerl
